apiVersion: v1
kind: Service
metadata:
  labels:
    app: my-apache
  name: my-apache
spec:
  ports:
  - port: 80
    protocol: TCP
    targetPort: 80
  selector:
    app: my-apache
  type: NodePort
status:
  loadBalancer: {}